TK_basdat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import login_register.urls as login_register
import daftar_beasiswa.urls as daftar_beasiswa
import acc_pendaftar_beasiswa.urls as acc_pendaftar
import register_beasiswa.urls as register_beasiswa
import info_beasiswa.urls as info_beasiswa
from login_register.views import home, logout


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name="home"),
    url(r'^logout/', logout, name="logout"),
    url(r'^account/', include(login_register,namespace='account')),
    url(r'^mahasiswa/', include(daftar_beasiswa, namespace='regis_beasiswa')),
    url(r'^donatur/', include(acc_pendaftar, namespace='penerimaan')),
    url(r'^register_beasiswa/', include(register_beasiswa, namespace='register_beasiswa')),
    url(r'^info_beasiswa/', include(info_beasiswa, namespace='info_beasiswa')),
]

register_beasiswa/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^daftar', register_beasiswa, name='register_beasiswa'),
    url(r'^tambah', register_beasiswa_tambah, name='register_beasiswa_tambah'),
    url(r'^message_post_daftar', message_post_daftar, name='message_post_daftar'),
    url(r'^message_post_tambah', message_post_tambah, name='message_post_tambah'),
]

register_beasiswa/models.py
from django.db import models, connection


# Create your models here.
class DataCommand(models.Manager):

	def insert_data(self, data):
		base_sql = "INSERT INTO SKEMA_BEASISWA (kode, nama, jenis, deskripsi, nomor_identitas_donatur) values("
		sql_command = []
		kumpulan_data = []

		for tmp in data:
			sql_command.append("(%s)" % ','.join(tmp))
			kumpulan_data.extend(tmp)

		sql = '%s%s' % (base_sql, ', '.join(sql_command))

		curs = connection.cursor()
		curs.execute(sql, kumpulan_data)

class DataBeasiswa(models.Model):
	
	command = DataCommand()

register_beasiswa/forms.py
from django import forms
from django.db import connection
from django.contrib.admin.widgets import AdminDateWidget

jenis_beasiswa=[
		('prestasi', 'Beasiswa Prestasi Akademik'),
		('bantuan_belajar', 'Beasiswa Bantuan Belajar'),
		('tugas_akhir', 'Beasiswa Bantuan Tugas Akhir')
	]

cursor=connection.cursor()
nomor_identitas_donatur = 'GDI68-7723283'
cursor.execute("SET search_path to SIMBION;")
cursor.execute("SELECT kode FROM SKEMA_BEASISWA WHERE nomor_identitas_donatur='"+nomor_identitas_donatur+"';")
kode_beasiswa= []
for p in list(cursor.fetchall()):
    #p = p.replace("(", "").replace(",)", "")
    print(p[0])
    kode_beasiswa.append((str(p[0]), p[0]))


class Message_Form_Daftar(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan link',
    }
    attrs = {
        'class': 'form-control'
    }
    description_attrs = {
        'type': 'text',
        'rows': 2,
        'class': 'status-form-textarea form-control',
    }

    kode = forms.CharField(label='Kode', required=True, max_length=27, widget=forms.TextInput(attrs=attrs))
    nama_paket_beasiswa = forms.CharField(label = 'Nama Paket Beasiswa', required=True, widget=forms.TextInput(attrs=attrs))
    jenis_paket_beasiswa =  forms.CharField(label='Jenis Paket Beasiswa', widget=forms.Select(choices=jenis_beasiswa, attrs=attrs))
    deskripsi = forms.CharField(label='Deskripsi', max_length=50,required=True, widget=forms.Textarea(attrs=description_attrs))
    syarat_beasiswa = forms.CharField(label = 'Syarat Beasiswa', initial='Tolong pisahkan syarat beasiswa dengan karakter ";"', required=True, widget=forms.TextInput(attrs=attrs))


class Message_Form_Tambah(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan link',
    }
    attrs = {
        'class': 'form-control'
    }

    date_attrs = {
        'type' : "date",        
    }

    kode_tambah = forms.CharField(label='Kode Beasiswa', widget=forms.Select(choices=kode_beasiswa, attrs=attrs))
    nomor_urut = forms.IntegerField(label='Nomor Urut', required=True, widget=forms.TextInput(attrs=attrs))
    tanggal_mulai = forms.DateField(label='Tanggal Mulai Pendaftaran',required=True, widget = AdminDateWidget(attrs = date_attrs))
    tanggal_tutup = forms.DateField(label='Tanggal Tutup Pendaftaran',required=True, widget = AdminDateWidget(attrs = date_attrs))

register_beasiswa/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.db import connections
from .forms import *
from .models import *
import datetime
# Create your views here.
response = {}
kode_beasiswa = []
cursor=connection.cursor()
cursor.execute("SET search_path to SIMBION;")
nomor_identitas_donatur = 'GDI68-7723283'

def register_beasiswa(request):
    response['form'] = Message_Form_Daftar	
    return render(request, 'register_beasiswa.html', response)

def register_beasiswa_tambah(request):
    response['form2'] = Message_Form_Tambah
    return render(request, 'register_beasiswa_2.html', response)

def message_post_daftar(request):
    form = Message_Form_Daftar(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        if (cek_kode(request.POST['kode']) == True):
            print("tullll")
            kode = request.POST['kode'] 
            nama_paket_beasiswa = request.POST['nama_paket_beasiswa']
            jenis_paket_beasiswa = request.POST['jenis_paket_beasiswa']
            deskripsi = request.POST['deskripsi']
            syarat_beasiswa = request.POST['syarat_beasiswa'].split(";")
            #nomor_identitas_donatur = get_nomor_identitas_donatur()
            values = "'"+kode+"','"+nama_paket_beasiswa+"','"+jenis_paket_beasiswa+"','"+deskripsi+"','"+nomor_identitas_donatur+"'"
            sql = "insert into skema_beasiswa (kode, nama, jenis, deskripsi, nomor_identitas_donatur) values ("+values+")"
            cursor.execute(sql)
            insert_into_syarat(syarat_beasiswa, kode)
            response['status'] = "Done"
            return HttpResponseRedirect('/register_beasiswa/daftar/')
        else:
            print("salah :(")
            response['status'] = "Fail"
            return HttpResponseRedirect('/register_beasiswa/daftar/')
    else:
        response['status'] = "Fail"
        return HttpResponseRedirect('/register_beasiswa/daftar/')

def cek_kode(kode):
	cursor.execute("SELECT kode FROM SKEMA_BEASISWA WHERE kode=%s", [kode])
	hasil = cursor.fetchone()
	if (hasil is None):
		print('sabiduy')
		return True
	else:
		print(hasil)
		print('gagal')
		return False

def get_nomor_identitas_donatur(username):
	cursor.execute("SELECT d.nomor_identitas FROM DONATUR d, PENGGUNA p WHERE p.username = '"+username+"' AND p.username=d.username")
	hasil = cursor.fetchone()
	return hasil

def message_post_tambah(request):
    form = Message_Form_Tambah(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        if (cek_no_urut(request.POST['nomor_urut'], request.POST['kode_tambah']) == True):
            print("tullll")
            kode_tambah = request.POST['kode_tambah'] 
            nomor_urut = request.POST['nomor_urut']
            tanggal_mulai = request.POST['tanggal_mulai']
            tanggal_tutup = request.POST['tanggal_tutup']
            jumlah_pendaftar = str(0)
            print(tanggal_tutup)
            periode = str(date_period(tanggal_mulai,tanggal_tutup)) + "Hari"
            status = get_status_period(tanggal_mulai,tanggal_tutup)
            values = "'"+kode_tambah+"','"+nomor_urut+"','"+tanggal_mulai+"','"+tanggal_tutup+"','"+periode+"','"+status+"', '"+jumlah_pendaftar+"'"
            sql = "insert into skema_beasiswa_aktif (kode_skema_beasiswa, no_urut, tgl_mulai_pendaftaran, tgl_tutup_pendaftaran, periode_penerimaan, status, jumlah_pendaftar) values ("+values+")"
            cursor.execute(sql)
            response['status'] = "Done"
            return HttpResponseRedirect('/register_beasiswa/tambah/')
        else:
            print("salah :(")
            response['status'] = "Fail"
            return HttpResponseRedirect('/register_beasiswa/tambah/')
    else:
        response['status'] = "Fail"
        return HttpResponseRedirect('/register_beasiswa/tambah/')

def cek_no_urut(no_urut, kode):
	cursor.execute("SELECT no_urut FROM SKEMA_BEASISWA_AKTIF WHERE no_urut='"+no_urut+"' AND kode_skema_beasiswa='"+kode+"'")
	hasil = cursor.fetchone()
	if (hasil is None):
		print('sabiduy')
		return True
	else:
		print(hasil)
		print('gagal')
		return False

def date_period(date_mulai, date_tutup):
	date_mulai = date_mulai.split("-")
	date_tutup = date_tutup.split("-")
	year = int(date_tutup[0]) - int(date_mulai[0])
	month = int(date_tutup[1]) - int(date_mulai[1])
	day = int(date_tutup[2]) - int(date_mulai[2])
	period = 0
	if (day < 0):
		day += 30
	period += (year*365)
	period += (month*30)
	period += day
	return period

def insert_into_syarat(syarat, kode):
	for p in syarat:
		cursor.execute("insert into syarat_beasiswa (kode_beasiswa, syarat) values ('"+kode+"', '"+p+"');")


def get_status_period(date_mulai, date_tutup):
	status = "Tidak Aktif"
	now = str(datetime.datetime.now().date()).split("-")
	now = list(map(int, now))
	date_tutup = list(map(int, date_tutup.split("-")))
	date_mulai = list(map(int, date_mulai.split("-")))
	if ((date_mulai[0] <= now[0] <= date_tutup[0]) or (date_mulai[1] <= now[1] <= date_tutup[1]) or (date_mulai[2] <= now[2] <= date_tutup[2])):
		status = "AKtif"
	return status

register_beasiswa/templates/register_beasiswa.html
{% extends "layout/base.html" %}
{% block title %}
Pendaftaran Beasiswa
{% endblock %}
{% block content %}
<style> 
form {
    margin-top:20%;
    width: 800px;
    margin:0 auto;
    max-width:60%;
    max-height: 70%
    padding:80px;
}

.w3-container {
    margin-top:3%;
    margin-left:60px;
    margin-right:60px;
}
#delete-button{
  border: #5DBCD2 solid 2px;
  text-align: center;
  border-radius: 5px;
  background-color: #5DBCD2;
  color: white;
  -webkit-transition-duration: 0.4s; /* Safari */
  transition-duration: 0.4s;
}

#delete-button:hover{
  border: #5DBCD2 solid 2px;
  text-align: center;
  border-radius: 5px;
  background-color: white;
  color: #5DBCD2;
}
#submit{
  width: 10vw;
  margin-left: inherit;
  margin-top: 10px;
  -webkit-transition-duration: 0.4s; /* Safari */
  transition-duration: 0.4s;
}
#submit:hover{
  background-color: white;
  color: #5DBCD2;
}
.flex{
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: flex-start;
  align-items: flex-start;
  align-content: flex-start;
  margin-bottom: 50px;
}
.flex-item{
  padding: 0 15px;
  flex-grow: 0;
  flex-shrink: 0;
  flex-basis: 30%;
  border-radius: 5px;
  background-color: white;
  padding: 15px;
  margin: 15px;
  height: 180px;
  min-width: 250px;
}


.name{
  text-align: center;
}
.link{
  text-align: center;
  padding-top: 15px;
}
.added-date{
  color:grey;
  padding: 10px;
}
.added-date:before{
  content: "";
  display: block;
  padding: 18px;
}
.added-date:after{
  content:"";
  display:block;
  background: #fff;
}

/* The alert message box */
.alert {
    padding: 20px;
    background-color: #f44336; /* Red */
    color: white;
    margin-bottom: 15px;
    text-align: center;
}
.alert.success {background-color: #4CAF50;}
/* The close button */
.closebtn {
    margin-left: 15px;
    color: white;
    font-weight: bold;
    float: right;
    font-size: 22px;
    line-height: 20px;
    cursor: pointer;
    transition: 0.3s;
}

/* When moving the mouse over the close button */
.closebtn:hover {
    color: black;
}
@media only screen and (max-width: 768px) {
  .flex-item{
    flex-basis: 90%;
  }
  #submit{
    margin-left: inherit;
    width: 150px;
  }
}
</style>

<div class="w3-container">
  <div class="w3-card-4">
    <header class="w3-container w3-light-blue">
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h1>Form Pendaftaran Beasiswa</h1>
    </header>
            <form cid="form" method="POST" action="{% url 'register_beasiswa:message_post_daftar' %}">   
                {% csrf_token %}
                {{form}}
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            <br>
            </form>
            {% if status == "Fail" %}
            <div class="alert">
              <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
              <strong>Kode sudah ada.</strong> Kode yang anda masukan sudah terdapat di database kami.  
            </div>
            {% elif status == "Done" %}
            <div class="alert success">
              <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>  
              <strong>Success!</strong> Beasiswa berhasil diproses.
              </div>
            {% endif %}       
            </div>  
        </div>
        <div class="col-md-4"></div>
    </div>
</div>


{% endblock %}

register_beasiswa/templates/register_beasiswa_2.html
{% extends "layout/base.html" %}
{% block title %}
Pendaftaran Beasiswa
{% endblock %}
{% block content %}
<style> 
[type="date"] {
  background:#fff url(https://cdn1.iconfinder.com/data/icons/cc_mono_icon_set/blacks/16x16/calendar_2.png)  97% 50% no-repeat ;
}
[type="date"]::-webkit-inner-spin-button {
  display: none;
}
[type="date"]::-webkit-calendar-picker-indicator {
  opacity: 0;
}

/* custom styles */
body {
  padding: 4em;
  background: #e5e5e5;
  font: 13px/1.4 Geneva, 'Lucida Sans', 'Lucida Grande', 'Lucida Sans Unicode', Verdana, sans-serif;
}
label {
  display: block;
}
input {
  border: 1px solid #c4c4c4;
  border-radius: 5px;
  background-color: #fff;
  padding: 3px 5px;
  box-shadow: inset 0 3px 6px rgba(0,0,0,0.1);
  width: 190px;
}
form {
    margin-top:20%;
    width: 800px;
    margin:0 auto;
    max-width:60%;
    max-height: 70%
    padding:80px;
}

.w3-container {
    margin-top:3%;
    margin-left:60px;
    margin-right:60px;
}
#delete-button{
  border: #5DBCD2 solid 2px;
  text-align: center;
  border-radius: 5px;
  background-color: #5DBCD2;
  color: white;
  -webkit-transition-duration: 0.4s; /* Safari */
  transition-duration: 0.4s;
}

#delete-button:hover{
  border: #5DBCD2 solid 2px;
  text-align: center;
  border-radius: 5px;
  background-color: white;
  color: #5DBCD2;
}
#submit{
  width: 10vw;
  margin-left: inherit;
  margin-top: 10px;
  -webkit-transition-duration: 0.4s; /* Safari */
  transition-duration: 0.4s;
}
#submit:hover{
  background-color: white;
  color: #5DBCD2;
}
.flex{
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: flex-start;
  align-items: flex-start;
  align-content: flex-start;
  margin-bottom: 50px;
}
.flex-item{
  padding: 0 15px;
  flex-grow: 0;
  flex-shrink: 0;
  flex-basis: 30%;
  border-radius: 5px;
  background-color: white;
  padding: 15px;
  margin: 15px;
  height: 180px;
  min-width: 250px;
}


.name{
  text-align: center;
}
.link{
  text-align: center;
  padding-top: 15px;
}
.added-date{
  color:grey;
  padding: 10px;
}
.added-date:before{
  content: "";
  display: block;
  padding: 18px;
}
.added-date:after{
  content:"";
  display:block;
  background: #fff;
}

/* The alert message box */
.alert {
    padding: 20px;
    background-color: #f44336; /* Red */
    color: white;
    margin-bottom: 15px;
    text-align: center;
}
.alert.success {background-color: #4CAF50;}
/* The close button */
.closebtn {
    margin-left: 15px;
    color: white;
    font-weight: bold;
    float: right;
    font-size: 22px;
    line-height: 20px;
    cursor: pointer;
    transition: 0.3s;
}

/* When moving the mouse over the close button */
.closebtn:hover {
    color: black;
}
@media only screen and (max-width: 768px) {
  .flex-item{
    flex-basis: 90%;
  }
  #submit{
    margin-left: inherit;
    width: 150px;
  }
}
</style>

<div class="w3-container">
  <div class="w3-card-4">
    <header class="w3-container w3-light-blue">
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h1>Form Pendaftaran Tambah Beasiswa Dari Paket</h1>
    </header>
            <form cid="form" method="POST" action="{% url 'register_beasiswa:message_post_tambah' %}">   
                {% csrf_token %}
                {{form2}}
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            <br>
            </form>
            {% if status == "Fail" %}
            <div class="alert">
              <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
              <strong>Kode sudah ada.</strong> Kode yang anda masukan sudah terdapat di database kami.  
            </div>
            {% elif status == "Done" %}
            <div class="alert success">
              <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>  
              <strong>Success!</strong> Beasiswa berhasil diproses.
              </div>
            {% endif %}       
            </div>  
        </div>
        <div class="col-md-4"></div>
    </div>
</div>


{% endblock %}